site_name: Statistical Learning with Python
pages:
  - Home: index.md
  - '2':
      - '2.1': 'sols/chapter2/exercise1.md'
      - '2.2': 'sols/chapter2/exercise2.md'
      - '2.3': 'sols/chapter2/exercise3.md'
      - '2.4': 'sols/chapter2/exercise4.md'
      - '2.5': 'sols/chapter2/exercise5.md'
      - '2.6': 'sols/chapter2/exercise6.md'
      - '2.7': 'sols/chapter2/exercise7.md'
      - '2.8': 'sols/chapter2/exercise8.md'
      - '2.9': 'sols/chapter2/exercise9.md'
      - '2.10': 'sols/chapter2/exercise10.md'   
  - '3':
      - '3.1': 'sols/chapter3/exercise1.md'
      - '3.2': 'sols/chapter3/exercise2.md' 
      - '3.3': 'sols/chapter3/exercise3.md' 
      - '3.4': 'sols/chapter3/exercise4.md'
      - '3.5': 'sols/chapter3/exercise5.md'  
      - '3.6': 'sols/chapter3/exercise6.md'
      - '3.7': 'sols/chapter3/exercise7.md'  
      - '3.8': 'sols/chapter3/exercise8.md'
      - '3.9': 'sols/chapter3/exercise9.md'
      - '3.10': 'sols/chapter3/exercise10.md'
      - '3.11': 'sols/chapter3/exercise11.md'
      - '3.12': 'sols/chapter3/exercise12.md'
      - '3.13': 'sols/chapter3/exercise13.md' 
      - '3.14': 'sols/chapter3/exercise14.md'
      - '3.15': 'sols/chapter3/exercise15.md'
  - '4':
      - '4.1': 'sols/chapter4/exercise1.md'
      - '4.2': 'sols/chapter4/exercise2.md'
      - '4.3': 'sols/chapter4/exercise3.md'
      - '4.4': 'sols/chapter4/exercise4.md'
      - '4.5': 'sols/chapter4/exercise5.md'
      - '4.6': 'sols/chapter4/exercise6.md'
      - '4.7': 'sols/chapter4/exercise7.md'
      - '4.8': 'sols/chapter4/exercise8.md'
      - '4.9': 'sols/chapter4/exercise9.md'
      - '4.10': 'sols/chapter4/exercise10.md'
      - '4.11': 'sols/chapter4/exercise11.md'
      - '4.12': 'sols/chapter4/exercise12.md'
      - '4.13': 'sols/chapter4/exercise13.md'
  - '5':
      - '5.1': 'sols/chapter5/exercise1.md'
      - '5.2': 'sols/chapter5/exercise2.md'
      - '5.3': 'sols/chapter5/exercise3.md'
      - '5.4': 'sols/chapter5/exercise4.md'
      - '5.5': 'sols/chapter5/exercise5.md'
      - '5.6': 'sols/chapter5/exercise6.md'
      - '5.7': 'sols/chapter5/exercise7.md'
      - '5.8': 'sols/chapter5/exercise8.md'
      - '5.9': 'sols/chapter5/exercise9.md'
  - '6':
      - '6.1': 'sols/chapter6/exercise1.md'
      - '6.2': 'sols/chapter6/exercise2.md'
      - '6.3': 'sols/chapter6/exercise3.md'
      - '6.4': 'sols/chapter6/exercise4.md'
      - '6.5': 'sols/chapter6/exercise5.md'
      - '6.6': 'sols/chapter6/exercise6.md'
      - '6.7': 'sols/chapter6/exercise7.md'
      - '6.8': 'sols/chapter6/exercise8.md'
      - '6.9': 'sols/chapter6/exercise9.md'
      - '6.10': 'sols/chapter6/exercise10.md'
      - '6.11': 'sols/chapter6/exercise11.md'  
  - '7':
      - '7.1': 'sols/chapter7/exercise1.md'
      - '7.2': 'sols/chapter7/exercise2.md'
      - '7.3': 'sols/chapter7/exercise3.md'
      - '7.4': 'sols/chapter7/exercise4.md'
      - '7.5': 'sols/chapter7/exercise5.md'
      - '7.6': 'sols/chapter7/exercise6.md'
      - '7.7': 'sols/chapter7/exercise7.md'
      - '7.8': 'sols/chapter7/exercise8.md'
      - '7.9': 'sols/chapter7/exercise9.md'
      - '7.10': 'sols/chapter7/exercise10.md'
      - '7.11': 'sols/chapter7/exercise11.md'
      - '7.12': 'sols/chapter7/exercise12.md'
  - '8':
      - '8.1': 'sols/chapter8/exercise1.md'
      - '8.2': 'sols/chapter8/exercise2.md'
      - '8.3': 'sols/chapter8/exercise3.md'
      - '8.4': 'sols/chapter8/exercise4.md'
      - '8.5': 'sols/chapter8/exercise5.md'
      - '8.6': 'sols/chapter8/exercise6.md'
      - '8.7': 'sols/chapter8/exercise7.md'
      - '8.8': 'sols/chapter8/exercise8.md'
      - '8.9': 'sols/chapter8/exercise9.md'
      - '8.10': 'sols/chapter8/exercise10.md'
      - '8.11': 'sols/chapter8/exercise11.md'
      - '8.12': 'sols/chapter8/exercise12.md'  
  - '9':
      - '9.1': 'sols/chapter9/exercise1.md'
      - '9.2': 'sols/chapter9/exercise2.md'
      - '9.3': 'sols/chapter9/exercise3.md'
      - '9.4': 'sols/chapter9/exercise4.md'
      - '9.5': 'sols/chapter9/exercise5.md'
      - '9.6': 'sols/chapter9/exercise6.md'
      - '9.7': 'sols/chapter9/exercise7.md'
      - '9.8': 'sols/chapter9/exercise8.md'
  - '10':
      - '10.1': 'sols/chapter10/exercise1.md'
      - '10.2': 'sols/chapter10/exercise2.md'
      - '10.3': 'sols/chapter10/exercise3.md'
      - '10.4': 'sols/chapter10/exercise4.md'
      - '10.5': 'sols/chapter10/exercise5.md'
      - '10.6': 'sols/chapter10/exercise6.md'
      - '10.7': 'sols/chapter10/exercise7.md'
      - '10.8': 'sols/chapter10/exercise8.md'
      - '10.9': 'sols/chapter10/exercise9.md'
      - '10.10': 'sols/chapter10/exercise10.md'
      - '10.11': 'sols/chapter10/exercise11.md'                         
  - About: about.md
theme: cinder



markdown_extensions:
   - pymdownx.arithmatex


extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
