site_name: Statistical Learning with Python
pages:
  - Home: index.md
  - '2':
      - '2.1': 'sols/chapter2/exercise1.md'
      - '2.2': 'sols/chapter2/exercise2.md'
      - '2.3': 'sols/chapter2/exercise3.md'
      - '2.4': 'sols/chapter2/exercise4.md'
      - '2.5': 'sols/chapter2/exercise5.md'
      - '2.6': 'sols/chapter2/exercise6.md'
      - '2.7': 'sols/chapter2/exercise7.md'
      - '2.8': 'sols/chapter2/exercise8.md'
      - '2.9': 'sols/chapter2/exercise9.md'
      - '2.10': 'sols/chapter2/exercise10.md'   
  - '3':
      - '3.1': 'sols/chapter3/exercise1.md'
      - '3.2': 'sols/chapter3/exercise2.md' 
      - '3.3': 'sols/chapter3/exercise3.md' 
      - '3.4': 'sols/chapter3/exercise4.md'  
  - '4':
      - '4.1': 'sols/chapter4/exercise1.md'
      - '4.2': 'sols/chapter4/exercise2.md'
      - '4.3': 'sols/chapter4/exercise3.md'
      - '4.4': 'sols/chapter4/exercise4.md'
      - '4.5': 'sols/chapter4/exercise5.md'
      - '4.6': 'sols/chapter4/exercise6.md'
      - '4.7': 'sols/chapter4/exercise7.md'
      - '4.8': 'sols/chapter4/exercise8.md'
      - '4.9': 'sols/chapter4/exercise9.md'
      - '4.10': 'sols/chapter4/exercise10.md'
      - '4.11': 'sols/chapter4/exercise11.md'
      - '4.12': 'sols/chapter4/exercise12.md'
      - '4.13': 'sols/chapter4/exercise13.md'
  - '5':
      - '5.1': 'sols/chapter5/exercise1.md'
      - '5.2': 'sols/chapter5/exercise2.md'
      - '5.3': 'sols/chapter5/exercise3.md'
      - '5.4': 'sols/chapter5/exercise4.md'
      - '5.5': 'sols/chapter5/exercise5.md'
      - '5.6': 'sols/chapter5/exercise6.md'
      - '5.7': 'sols/chapter5/exercise7.md'
      - '5.8': 'sols/chapter5/exercise8.md'
      - '5.9': 'sols/chapter5/exercise9.md'                  
  - About: about.md
theme: cinder



markdown_extensions:
   - pymdownx.arithmatex


extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
