site_name: Statistical Learning with Python
pages:
  - Home: index.md
  - '2':
      - '2.1': 'sols/chapter2/exercise1.md'
      - '2.2': 'sols/chapter2/exercise2.md'
      - '2.4': 'sols/chapter2/exercise4.md'
      - '2.5': 'sols/chapter2/exercise5.md'
  - About: about.md
theme: cinder



markdown_extensions:
   - pymdownx.arithmatex


extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
